说到异常处理自然就会想到try...catch
```
<?php
try{
  throw new Exception("test");
} catch (Exception $e) {
  var_dump($e->getMessage());
} finally {
  var_dump("finally");
}
```
一般框架都会自己封装Exception类，如HttpException或者NotFoundException等等，用这样来实现捕获不同类的异常，做不用的处理；如捕获了NotFoundException异常来加载404的专属页面，捕获HttpException异常去响应http code 200
```
<?php
class HttpException extends Exception{}
try {
	$e = new HttpException("test");
	throw $e;
} catch (HttpException $e) {
	var_dump($e->getMessage());
} catch (Exception $e) {
	var_dump($e->getMessage());
}
```
对于finally有一个需要注意一点，finally里面不能有return，会影响最后的返回结果
```
<?php
function test(){
	try {
		return 2;	
	} catch (Exception $e) {
	
	} finally {
		return 123;
	}
}
var_dump(test());  //123
```
